server:
  port: 0

spring:
  application:
    name: delivery

  datasource:
    url: jdbc:postgresql://localhost:12432/deliverydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always

  cloud:
    config:
      enabled: false

  config:
    import: "optional:configserver:"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/