spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:postgresql://localhost:8432/shopping_cart_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none         # Hibernate не создаёт/обновляет таблицы
    show-sql: true
  sql:
    init:
      mode: always           # schema.sql будет выполняться при старте

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka